spring:
  application:
    name: ai-car-sales
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app_db}
    username: ${DB_USER:app}
    password: ${DB_PASSWORD:app_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
